<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=8">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/tagaudio_Honore_benjamin.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=11">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/IHM_tag_audio.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=13">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/Tag_Audio.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=9">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/audiotag_anthony_souplet.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=14">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/interface_tagmusic.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=24">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/interace.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=16">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/tags-audios.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=17">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/interface_jeanbob.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=18">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/TAGAUDIO_COET_SALHAB.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=20">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/audiotag-2.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=21">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/sebastien-tag-audio.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=20">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/audiotag2.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=22">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/tagaudio.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=23">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/maquette_IHM.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=25">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/Tagaudio.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=26">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/IHM_TagAudio_ELABDALLAOUI_AMINA.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=27">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/WOLFF_JEREMY_Tag_Audio.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=28">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/tagAudioIHM.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=30">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/ihmAudioTag.svg" ></iframe>
<a href="http://miseencen.free.fr/spip/ecrire/?exec=articles&id_article=34">Lien spip</a><iframe width="100%" height="100%" src="http://miseencen.free.fr/spip/IMG/svg/mockup.svg" ></iframe>
